// packages/dragcave-translations/src/surfaces/settings/SettingsDialog.svelte
<script lang="ts">
  import { RM } from "src/localization";
  import { browserLanguage, knownLanguages, languageInfo } from "src/localization/languages";
  import { appSettings } from "src/settings";

  interface SettingsDialogProps {
    onclose?: () => void;
  }

  let language = $state(appSettings.language || "" as const);
  const autoLanguageAutonym = languageInfo[browserLanguage].autonym;
  const props: SettingsDialogProps = $props();

  const saveSettings = () => {
    appSettings.language = language || undefined;
  }

  const closeDialog = () => {
    dialogEl.close();
    props.onclose?.();
  }

  let dialogEl: HTMLDialogElement;
  $effect(() => {
    dialogEl.showModal();
  });
</script>

<dialog bind:this={dialogEl}>
  <h2>{RM.getMessage("AppName")}</h2>
  <h3>{RM.getMessage("Settings")}</h3>
  <form>
    <div>
      <label for="settings-language">{RM.getMessage("Language")}: </label>
      <select id="settings-language" name="language" bind:value={language}>
        <option value=""
          >{RM.getMessage("AutoDetect")}: {autoLanguageAutonym}</option
        >
        {#each knownLanguages as lang}
          <option value={lang}>{languageInfo[lang].autonym}</option>
        {/each}
      </select>
    </div>
    <menu>
      <button type="submit" onclick={() => {
        saveSettings();
        closeDialog();
      }}>{RM.getMessage("OK")}</button>
      <button onclick={closeDialog}>{RM.getMessage("Cancel")}</button>
    </menu>
  </form>
</dialog>

// packages/dragcave-translations/src/surfaces/settings/SettingsDialog.tsx
import { useMergedRefs } from "@fluentui/react-utilities";
import * as React from "react";
import { RM } from "src/localization";
import { browserLanguage, KnownLanguage, knownLanguages, languageInfo } from "src/localization/languages";
import { useObservableViewModelSelector } from "src/utils/observableViewModel";
import { SettingsViewModel } from "./settingsViewModel";
import { appSettings } from "src/settings";

export interface SettingsDialogProps {
  viewModel: SettingsViewModel;
}

export const SettingsDialog: React.FC<SettingsDialogProps> = props => {
  const { viewModel } = props;
  const dialogRef = useMergedRefs<HTMLDialogElement>(e => {
    if (!e) return;
    e.showModal();
  });
  const isOpened = useObservableViewModelSelector(viewModel, vm => vm.isOpened);
  const autoLanguageAutonym = React.useMemo(() => languageInfo[browserLanguage].autonym, []);
  const onSubmit = React.useCallback((formData: FormData) => {
    appSettings.language = formData.get("language") as KnownLanguage;
    viewModel.isOpened = false;
  }, []);
  if (!isOpened) return null;
  return <dialog ref={dialogRef}>
    <h2>{RM.getMessage("AppName")}</h2>
    <h3>{RM.getMessage("Settings")}</h3>
    <form action={onSubmit}>
      <div>
        <label htmlFor="settings-language">{RM.getMessage("Language")}: </label>
        <select id="settings-language" name="language" defaultValue={appSettings.language || ""}>
          <option value="">{RM.getMessage("AutoDetect")}: {autoLanguageAutonym}</option>
          {knownLanguages.map(l => <option key={l} value={l}>{languageInfo[l].autonym}</option>)}
        </select>
      </div>
      <menu>
        <button type="submit">{RM.getMessage("OK")}</button>
        <button onClick={() => viewModel.isOpened = false}>{RM.getMessage("Cancel")}</button>
      </menu>
    </form>
  </dialog>;
};
